### ISSUE TITLE
Training on MOVi with the default config doesn't work on a GPU with 24GB memory

### ISSUE THREAD

**Issue by mtangemann** [karazijal/probable-motion#1]
Hi,

Thanks a lot for making your code available. I am trying to train your model on MOVi-A with the default config:
```
python main.py --config config_sacnn.yaml UNSUPVIDSEG.DATASET MOVi_A
```

In the paper you mention training on a 24GB GPU with a batch size of 32. However training with the default config doesn't even fit on a 32GB GPU in my setup. Am I missing something? Did you train using a smaller batch size or using multiple GPUs? It would be great if you could provide more information on your setup and config.

Thank you,
Matthias

**Comment by karazijal** [comment]
Hi,
Thank you for your interest in our work. The comment in the paper is in reference to the models using Swin-Tiny which was our default config until after acceptance. Apologies for the confusion. Swin-T backbone (config `config_swin_tiny.yaml`) should requires around 14-15GB. It performs similarly or better in our experiments except maybe for very simple data. 

It should be possible to reduce memory footprint if desired. I would recommend first lowering the `UNSUPVIDSEG.LOSS_NPART = 1` and halving the batch size to fit things. In the specific SACNN case, I would consider also increasing the stride of early layers.

**Comment by mtangemann** [comment]
Indeed, switching to Swin-T backbone reduces the memory footprint substantially. Thanks a lot for the clarification.
