### ISSUE TITLE
Questions about Configuring Model for KITTI Dataset Training and Evaluation

### ISSUE THREAD

**Issue by XinruiGong** [karazijal/probable-motion#2]
Hi,

I am currently exploring the use of your model with the M2F with Swin+WL backbone for a project involving the KITTI dataset. I would be grateful if you could provide some insights into a few questions I have.

1. Dataset Organization: Could you please advise on the preferred structure for the KITTI dataset when training the model? I'm aiming to ensure that the dataset is correctly formatted for your training pipeline.

2. Configuration Changes: In preparation for training on the KITTI dataset, would I need to modify the settings within the `config_sacnn.yaml`? For instance, is the command `python main.py --config config_sacnn.yaml UNSUPVIDSEG.DATASET KITTI` appropriate for starting the training process, or are there other specific changes to the YAML configuration file that are recommended?

3. Model Evaluation: To accurately reproduce the results documented in the associated papers, could you outline the evaluation process for the trained model? Are there any particular scripts or evaluation metrics that should be followed?

Your assistance in clarifying these points would be highly appreciated, as it would greatly aid in my understanding and application of this model.

Thank you very much for your time and for the work you've shared with the community.

Warm regards,
Xinrui

**Comment by karazijal** [comment]
Hi,

Thank you for your interest in our work.

1. For organising the KITTI datasets, the most straightforward way to describe it would be to use the convention for DAVIS datasets:
```
data/KITTI/JPEGimages/<seq>/<frame>.png
data/KITTI/Flows_gap<gap>/<seq>/<frame>.flo
```
and similar. This is just to help the data loader find the files. Paths can be changed or adjusted with appropriate renames in the data loader parameters.
See [here](https://github.com/karazijal/probable-motion/blob/878fc9487731ee3316bd0f35e60b46a8233bf5f2/src/datasets/kitti_val.py#L54) and [here](https://github.com/karazijal/probable-motion/blob/878fc9487731ee3316bd0f35e60b46a8233bf5f2/src/datasets/flow_pair_detectron_new.py#L25) for code that indexes the files and their meaning.

2. For training on KITTI use configurations files that have end in `_kitti.yaml`  or `_kitti_wl.yaml`. There are either R18 or swin-t versions. The "small" CNN actually consumes a lot of memory. For this reason we used either Resnet18 (as in prior work) or SWIN Tiny backbones which have similar parameter counts but are much more memory efficient. 

3. The main metric for KITTI is ARI-FG, which the evaluator is already set to calculate (and others). You can just call `run_eval(...)` from [here](https://github.com/karazijal/probable-motion/blob/878fc9487731ee3316bd0f35e60b46a8233bf5f2/src/val.py#L49) after training is finished. To load the model outside of training scirpt, e.g. after training has finished, see notes in [MODELS.md](https://github.com/karazijal/probable-motion/blob/main/MODELS.md).

Best,

**Comment by XinruiGong** [comment]
Thanks a lot for your kind reply!
